services:
  ollama-api:
    image: 'ollama/ollama:latest'
    volumes:
      - 'ollama:/root/.ollama'
    healthcheck:
      test:
        - CMD
        - ollama
        - list
      interval: 5s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
  ollama-api:
    image: 'ollama/ollama:rocm'
    volumes:
      - 'ollama:/root/.ollama'
    healthcheck:
      test:
        - CMD
        - ollama
        - list
      interval: 5s
      timeout: 30s
      retries: 10
      devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
      
  open-webui:
    image: 'ghcr.io/open-webui/open-webui:main'
    volumes:
      - 'open-webui:/app/backend/data'
    depends_on:
      - ollama-api
    environment:
      - SERVICE_FQDN_OLLAMA_8080
      - 'OLLAMA_BASE_URL=http://ollama-api:11434'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080'
      interval: 5s
      timeout: 30s
      retries: 10
